### ISSUE TITLE
Get started, How to run?

### ISSUE THREAD

**Issue by markosii** [ReedD/crawler#1]
Hi,

I want to test your module "crawler", I did : `git clone https://github.com/ReedD/crawler.git`

Then `npm install`

=> All packages are succefully installed

I don't know how to run it, because when I did `./crawl -u https://www.dadoune.com` I have this error

`',' is not recognized as an internal or external command`

I tried with `crawl -u https://www.dadoune.com` but I have the same error.

Thanks

**Comment by ReedD** [comment]
@markosii I've never seen that error. Try running it with `DEBUG` on:
```bash
DEBUG=crawler:* ./crawl -u https://www.dadoune.com
```
And see if there is more info.

**Comment by markosii** [comment]
Thanks for reply,

I just did this : 

`DEBUG=crawler:* ./crawl -u https://www.dadoune.com`


and I have this error : 
```

crawler:mongo Drop page collection +0ms
(node:130492) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): MongoError: ns not found
(node:130492) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1153:14)



```

**Comment by 5shekel** [comment]
my experience a bit different.
`DEBUG=crawler:* ./crawl -u https://www.dadoune.com`
after complaining it didn't have mongod running
`(node:11337) UnhandledPromiseRejectionWarning: MongoError: failed to connect to server 
[localhost:27017] on firstconnect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]`

 i installed and started mongodb 
`pacman -S mongdb && systemctl start mongodb`

then i get 
```
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1121:14)
Emitted 'error' event at:
    at RedisClient.on_error (/home/yair/dev/crawler/node_modules/redis/index.js:406:14)
    at Socket.<anonymous> (/home/yair/dev/crawler/node_modules/redis/index.js:279:14)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
```

**Comment by ReedD** [comment]
Do you have redis installed and running? If not you need to.
